name: Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  deployments: write

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            platform: windows
            arch: x86_64
            target: win32-x64
            ext: zip
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            target: linux-x64
            ext: tar.gz

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Install Dependencies
        run: npm run install:all

      - name: Compile Webview
        run: npm run build:webview

      - name: Compile Extension
        run: npm run compile

      - name: Download server executable
        uses: robinraju/release-downloader@v1.8
        with:
          repository: albertziegenhagel/snail-server
          tag: head
          fileName: snail-server-${{ matrix.arch }}-${{ matrix.platform }}.${{ matrix.ext }}
          out-file-path: server
          extract: true

      - name: Package
        run: |
          rm server/snail-server-${{ matrix.arch }}-${{ matrix.platform }}.${{ matrix.ext }}
          vsce package --target ${{ matrix.target }} --pre-release

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with: 
          name: snail-${{ matrix.target }}
          path: ${{ github.workspace }}/*.vsix
